itsav.es:
    build: "./docker/"
    ports:
        - "3333:3333"
    volumes:
        - ./:/app
    environment:
        - VIRTUAL_HOST=dev.itsav.es
    tty: true
    links:
        - db.itsav.es:db-dev.itsav.es

db.itsav.es:
    image: mariadb:10.3
    ports:
        - "3306:3306"
    environment:
        - VIRTUAL_HOST=db-dev.itsav.es
        - MYSQL_ROOT_PASSWORD=root-itsaves
        - MYSQL_DATABASE=itsaves
